export const ADD_AR_OBJECT = 'ADD_AR_OBJECT';
export const CLEAR_AR_OBJECTS = 'CLEAR_AR_OBJECTS';
export const REMOVE_AR_OBJECT = 'REMOVE_AR_OBJECT'
export const UPDATE_GYRO_DATA = 'UPDATE_GYRO_DATA';