# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'mobileapp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for mobileapp
    pod 'Google/SignIn'
    pod 'Firebase/Core'
  target 'mobileapp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'mobileappTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'mobileapp-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for mobileapp-tvOS


end
